# public/Dockerfile.web
FROM python:3.12-slim

WORKDIR /app

COPY public/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

# Set environment variables for Django
ENV DJANGO_SETTINGS_MODULE=app_1.settings_public
ENV PYTHONUNBUFFERED=1

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]