version: '3'

services:
  api:
    build:
      context: ./django-site/app_1/
      dockerfile: Dockerfile.api
    # environment:
    #   - DJANGO_SETTINGS_MODULE=app_1.settings
    volumes:
      - ./django-site/app_1:/app 
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    networks:
      - back  # API reste dans le réseau back

  public:
    build:
      context: ./django-site/app_1/
      dockerfile: Dockerfile.web
    # environment:
    #   - DJANGO_SETTINGS_MODULE=app_1.settings
    volumes:
      - ./django-site/app_1:/app
    # ports:
    #   - "8001:8001"
    depends_on:
      - db
    networks:
      - front  # Public reste dans le réseau front

  proxy:
    build:
      context: ./django-site/app_1/
      dockerfile: Dockerfile.proxy
    ports:
      - "80:80"
    volumes:
      - ./django-site/app_1/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - public
    networks:
      - front  # Proxy connecté aux deux réseaux
      - back

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tsp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - front

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - back
      - front

volumes:
  postgres_data:

networks:
  back:
  front:
